export const PUSH_PROMPT_ENGAGEMENT_DELAY_MS = 25_000;
export const PUSH_PROMPT_SUPPRESSION_RETRY_MS = 5_000;
export const PUSH_PROMPT_TRANSITION_MS = 400;
export const PUSH_PROMPT_SUCCESS_DISPLAY_MS = 1_800;
